fragment PageInfoFragment on PageInfo {
  endCursor
  startCursor
  hasNextPage
  hasPreviousPage
}

fragment UserFragment on User {
  id
  activePlan {
    ...PlanFragment
  }
  contactNumber
  email
  firstName
  isActive
  isArchived
  isDeleted
  isRoot
  jobTitle
  lastName
  password
  secondAuthEnabled
}

fragment AttachmentFragment on Attachment {
  id
  description
  fileName
  label
  url
  s3Bucket
  s3Key
}

fragment PlanFragment on Plan {
  id
  company {
    id
  }
  is_active
  is_archived
  is_deleted
  max_users
  name
  price
}

fragment AddressFragment on Address {
  id
  street
  city
  state
  country
  postCode
  latitude
  longitude
}

fragment ContactFragment on Contact {
  id
  name
  surname
  email
  mobileCode
  mobileNumber
  landlineCode
  landlineNumber
}

fragment CompanyShortFragment on Company {
  id
  name
}

fragment CompanyMemberFragment on CompanyMember {
  id
  company {
    ...CompanyShortFragment
  }
  isArchived
  isDeleted
  role
  status
  user {
    ...UserFragment
  }
}

fragment CompanyFragment on Company {
  id
  bankAccount
  # {
  #   name
  #   code
  #   accountNumber
  #   description
  # }
  businessType
  country
  currency
  govNumber
  isArchived
  legalName
  logo {
    ...AttachmentFragment
  }
  name
  salesTax
  timeSheetSettings
  # {
  #   autoSendInvoices
  #   groupEvery
  #   workingHours
  #   approvalsEnabled
  # }
  websiteURL
  addresses {
    ...AddressFragment
  }
  contacts {
    ...ContactFragment
  }
  companyMembers {
    ...CompanyMemberFragment
  }
}

fragment ServiceFragment on Service {
  id
  billingType
  company {
    ...CompanyShortFragment
  }
  includeConsTax
  isArchived
  isDeleted
  isTemplate
  name
  timeBasedType
  totalAmount
}

fragment CustomerFragment on Customer {
  id
  company {
    ...CompanyShortFragment
  }
  description
  govNumber
  isArchived
  isDeleted
  name
  addresses {
    ...AddressFragment
  }
  contacts {
    ...ContactFragment
  }
}

fragment ProjectServiceRuleFragment on ProjectServiceRule {
  id
  projectService {
    id
  }
  amount
  percent
  type
  isPercent
}

fragment ProjectServiceFragment on ProjectService {
  id
  amount
  isArchived
  isDeleted
  project {
    id
  }
  rules {
    ...ProjectServiceRuleFragment
  }
  service {
    ...ServiceFragment
  }
}

fragment ProjectFragment on Project {
  id
  company {
    ...CompanyShortFragment
  }
  customer {
    ...CustomerFragment
  }
  description
  endsAt
  isArchived
  isDeleted
  name
  projectService {
    ...ProjectServiceFragment
  }
  startsAt
  status
}

fragment TimeSheetEntryFragment on TimeSheetEntry {
  id
  date
  duration
  isArchived
  isDeleted
  isInvoiced
  timeSheet {
    id
  }
  customer {
    ...CustomerFragment
  }
  project {
    ...ProjectFragment
  }
  service {
    ...ServiceFragment
  }
}

fragment TimeSheetFragment on TimeSheet {
  id
  attachments {
    ...AttachmentFragment
  }
  company {
    ...CompanyShortFragment
  }
  endsAt
  isArchived
  isDeleted
  number
  preview {
    ...AttachmentFragment
  }
  startsAt
  status
  timeSheetEntries(where: $timeSheetEntryWhere, orderBy: date_ASC) {
    ...TimeSheetEntryFragment
  }
  user {
    ...UserFragment
  }
}

fragment InvoiceItemEntryFragment on InvoiceItemEntry {
  id
  order
  description
  name
  price
  quantity
  tax
  invoice {
    id
  }
  project {
    ...ProjectFragment
  }
  service {
    ...ServiceFragment
  }
  timeSheetEntry {
    ...TimeSheetEntryFragment
  }
  timeSheet {
    ...TimeSheetFragment
  }
}

fragment InvoiceFragment on Invoice {
  id
  title
  attachments {
    ...AttachmentFragment
  }
  buyer {
    ...CustomerFragment
  }
  number
  description
  invoiceDate
  dueDate
  preview {
    ...AttachmentFragment
  }
  items {
    ...InvoiceItemEntryFragment
  }
  seller {
    ...CompanyFragment
  }
  status
  type
  total
}

fragment MainAccountFragment on MainAccount {
  id
  company {
    ...CompanyShortFragment
  }
  code
  name
  type
  isArchived
  isDeleted
}

fragment LedgerTransactionFragment on LedgerTransaction {
  id
  mainAccount {
    ...MainAccountFragment
  }
  drcr
  amount
  currency
  date
  company {
    ...CompanyShortFragment
  }
  isArchived
  isDeleted
}

fragment LedgerPostingFragment on LedgerPosting {
  id
  mainAccount {
    ...MainAccountFragment
  }
  postingType
  isArchived
  isDeleted
}

fragment LedgerJournalFragment on LedgerJournal {
  id
  total
  description
  currency
  includeConsTax
  posted
  company {
    ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment AssetGroupFragment on AssetGroup {
  id
  name
  depreciationType
  usefulLife
  company {
    ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment AssetFragment on Asset {
  id
  name
  assetGroup {
    ...AssetGroupFragment
  }
  dateOfAquisition
  aquisitionPrice
  netBookValue
  depreciation
  salvageValue
  company {
    ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment BankTransactionFragment on BankTransaction {
  id
  transactionDate
  amount
  description
  company {
    ...CompanyShortFragment
  }
  isArchived
  isDeleted
}

fragment PbsOrganisationFragment on PbsOrganisation {
  id
  code
  title
  street
  city
  stateAddress
  postcode
  phone
  effectiveFrom
  effectiveTo
  isArchived
  isDeleted
}

fragment PbsTPPFragment on PbsTPP {
  id
  snomedCode
  clinicalPreferredTerm
  packSize
  brandName
  exManufacturerPrice
  # Temporary comment it out
  # pricingModel
  mpp_id
  organisation_id {
    ...PbsOrganisationFragment
  }
  effectiveFrom
  effectiveTo
  isArchived
  isDeleted
}

fragment InventoryFragment on Inventory {
  id
  name
  inventoryModel
  uom
  company {
    ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment WareHouseFragment on WareHouse {
  id
  name
  company {
    ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment SalesOrderFragment on SalesOrder {
  id
  customer {
    ...CustomerFragment
  }
  transactionDate
  currency
  company {
    ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment SalesOrderLineFragment on SalesOrderLine {
  id
  salesOrder {
    ...SalesOrderFragment
  }
  inventory {
    ...InventoryFragment
  }
  qty
  isArchived
  isDeleted
}

fragment SupplierFragment on Supplier {
  id
  name
  address {
    ...AddressFragment
  }
  termsOfPayment
  bankAccount
  emailAddressForRemittance
  company{
   ...CompanyFragment
  }
  isArchived
  isDeleted
}

fragment PurchaseOrderFragment on PurchaseOrder {
  id
  pbsOrganisation
  date
  orderer {
    ...UserFragment
  }
  status
  supplier {
    ...SupplierFragment
  }
  isArchived
  isDeleted
}

fragment PoReceiptFragment on PoReceipt {
  id
  receiptNumber
  purchaseOrder {
    ...PurchaseOrderFragment
  }
  receiptDate
  isArchived
  isDeleted
}

fragment PurchaseOrderLineFragment on PurchaseOrderLine {
  id
  item {
    ...InventoryFragment
  }
  qty
  unit
  unitPrice
  site {
    ...WareHouseFragment
  }
  purchaseOrder {
    ...PurchaseOrderFragment
  }
  poReceipt {
    ...PoReceiptFragment
  }
  isArchived
  isDeleted
}