#import "./commonFragments.gql"

query companies($joined: Boolean, $created: Boolean) {
  companies(joined: $joined, created: $created) {
    ...CompanyFragment
  }
}

query company($where: WhereUniqueInput) {
  company(where: $where) {
    ...CompanyFragment
  }
}

# Create Company
mutation createCompany($data: kCompanyCreateInput!) {
  createCompany(data: $data) {
    ...CompanyFragment
  }
}

# update Company
mutation updateCompany($data: kCompanyUpdateInput!, $where: WhereUniqueInput!) {
  updateCompany(data: $data, where: $where) {
    ...CompanyFragment
  }
}
