#import "./commonFragments.gql"

# delete Company Member
mutation updateCompanyMember(
  $data: kCompanyMemberUpdateInput!
  $where: WhereUniqueInput!
) {
  updateCompanyMember(data: $data, where: $where) {
    ...CompanyMemberFragment
  }
}

# delete Company Member
mutation deleteCompanyMember($id: ID!) {
  deleteCompanyMember(id: $id) {
    success
  }
}
